apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quote-app
spec:
  serviceName: "quote-app-service"
  replicas: 1
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
      - name: quote-app
        image: quote-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: web
        volumeMounts:
        - name: data-volume
          mountPath: /usr/src/app/data
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
